#!/bin/bash

# Railway Deployment Script for Creator Hub
# This script helps deploy the Creator Hub application to Railway

set -e

echo "🚀 Creator Hub - Railway Deployment Script"
echo "==========================================="

# Check if Railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo "❌ Railway CLI is not installed. Please install it first:"
    echo "   npm install -g @railway/cli"
    echo "   or visit: https://docs.railway.app/develop/cli"
    exit 1
fi

echo "✅ Railway CLI found"

# Login to Railway (if not already logged in)
echo "🔐 Checking Railway authentication..."
if ! railway whoami &> /dev/null; then
    echo "Please login to Railway:"
    railway login
fi

echo "✅ Railway authentication successful"

# Create new Railway project or link existing one
echo "📦 Setting up Railway project..."
read -p "Do you want to create a new Railway project? (y/n): " create_new

if [[ $create_new == "y" || $create_new == "Y" ]]; then
    echo "Creating new Railway project..."
    railway init
else
    echo "Linking to existing Railway project..."
    railway link
fi

# Set up environment variables
echo "🔧 Setting up environment variables..."
echo "Please set the following environment variables in Railway dashboard:"
echo ""
echo "Backend Service:"
echo "- NODE_ENV=production"
echo "- PORT=5000"
echo "- DATABASE_URL=(will be auto-generated by Railway PostgreSQL)"
echo "- JWT_SECRET=(generate a secure secret)"
echo "- CORS_ORIGIN=https://your-frontend-domain.railway.app"
echo ""
echo "Frontend Service:"
echo "- VITE_API_URL=https://your-backend-domain.railway.app"
echo ""

# Create railway.json configuration
echo "📝 Creating Railway configuration..."
cat > railway.json << EOF
{
  "\$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "DOCKERFILE",
    "dockerfilePath": "infra/Dockerfile.backend"
  },
  "deploy": {
    "numReplicas": 1,
    "sleepApplication": false,
    "restartPolicyType": "ON_FAILURE"
  }
}
EOF

# Create separate railway.json for frontend
cat > railway.frontend.json << EOF
{
  "\$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "DOCKERFILE",
    "dockerfilePath": "infra/Dockerfile.frontend"
  },
  "deploy": {
    "numReplicas": 1,
    "sleepApplication": false,
    "restartPolicyType": "ON_FAILURE"
  }
}
EOF

echo "✅ Railway configuration created"

# Deploy services
echo "🚀 Deploying to Railway..."
echo "Note: You'll need to deploy backend and frontend as separate services"
echo ""
echo "1. Deploy Backend:"
echo "   - Create a new service in Railway"
echo "   - Connect your GitHub repository"
echo "   - Set the dockerfile path to: infra/Dockerfile.backend"
echo "   - Add PostgreSQL database service"
echo "   - Set environment variables"
echo ""
echo "2. Deploy Frontend:"
echo "   - Create another service in Railway"
echo "   - Connect the same GitHub repository"
echo "   - Set the dockerfile path to: infra/Dockerfile.frontend"
echo "   - Set VITE_API_URL to your backend service URL"
echo ""

read -p "Press Enter to continue with automatic deployment (or Ctrl+C to deploy manually)..."

# Attempt automatic deployment
echo "Deploying backend service..."
cp railway.json railway.json.bak
railway up --detach

echo "✅ Deployment initiated!"
echo "📊 Check your deployment status at: https://railway.app/dashboard"
echo ""
echo "🔗 Next steps:"
echo "1. Wait for deployment to complete"
echo "2. Set up custom domains if needed"
echo "3. Configure environment variables"
echo "4. Run database migrations: railway run npx prisma migrate deploy"
echo "5. Test your application"
echo ""
echo "🎉 Railway deployment script completed!"